site_name: PattesThai
site_description: Refuge temporaire pour chiens et chats errants en danger en Thaïlande
site_author: Équipe PattesThai

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    logo: material/paw
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Accueil: index.md
  - Campagne de Financement: campaign/funding.md
  - Rapports: reports/README.md

repo_url: https://github.com/Casius999/PattesThai
repo_name: Casius999/PattesThai

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde