name: Deploy Documentation

on:
  # Workflow manuel pour déclencher un déploiement instantané
  workflow_dispatch:
  # Publication automatique lorsque la documentation est mise à jour
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    branches:
      - main

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
        
    - name: Build documentation
      run: mkdocs build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Déploiement automatique de la documentation'