name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Exécution hebdomadaire, chaque dimanche à minuit
  workflow_dispatch:  # Permet l'exécution manuelle

permissions:
  contents: read
  security-events: write

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Analyse de sécurité avec Bandit
    - name: Run Bandit Security Analysis
      run: |
        mkdir -p security-reports
        bandit -r . -x tests,venv -f json -o security-reports/bandit-report.json || true
        echo "Résultats de l'analyse Bandit:"
        if [ -f security-reports/bandit-report.json ]; then
          echo "Bandit a terminé son analyse. Voir le rapport complet dans les artefacts."
        else
          echo "Aucun problème détecté par Bandit"
        fi

    # Upload des rapports de sécurité
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: security-reports/
        retention-days: 30
      continue-on-error: true